Fixed iPhone 64bit CPU A8 Compatible.

diff --git a/BuildForIphone b/BuildForIphone
--- a/BuildForIphone
+++ b/BuildForIphone
@@ -5,7 +5,8 @@ MAKE_LOGS="${PREFIX}/log";
 NETSNMPDIR="${PREFIX}/tmp";
 OPENSSLDIR="$(pwd)/openssl-for-iphone";
 CROSS_DEVELOPER="$(xcode-select -print-path)";
-ARCHS="armv7 arm64 i386 armv7s"
+#ARCHS="x86_64 i386 armv7 armv7s arm64"
+ARCHS="arm64"
 
 PS3="please select iOS version > "
 select item in $(xcodebuild -showsdks | grep iphoneos | awk '{print $NF}' | sed -e "s@iphoneos@@g")
@@ -28,7 +29,7 @@ done
 SDKVER=${item};
 
 for arch in ${ARCHS}; do
-    if [[ "${arch}" == "i386" ]]; then
+    if [[ "${arch}" == "i386" ]] || [[ "${arch}" == "x86_64" ]]; then
         export CROSS_TYPE=Simulator
     else
         export CROSS_TYPE=OS
@@ -40,8 +41,6 @@ for arch in ${ARCHS}; do
     SDK_DIR="${CROSS_TOP}/SDKs/${CROSS_SDK}";
     TOOL_DIR="${CROSS_DEVELOPER}/Toolchains/XcodeDefault.xctoolchain";
 
-    export PATH="${TOOL_DIR}/usr/bin:${PATH}";
-
     cc=${CROSS_DEVELOPER}/usr/bin/gcc;
     ld=${CROSS_DEVELOPER}/usr/bin/ld;
     ar=${TOOL_DIR}/usr/bin/ar;
@@ -49,27 +48,20 @@ for arch in ${ARCHS}; do
     host=$(${cc} -arch ${arch} -v 2>&1 | grep "Target" | awk '{print $2}');
     target=${host};
 
-    CFLAGS="-with-cflags=\"";
-    CFLAGS="-arch ${arch} ";
-#    CFLAGS="${CFLAGS} --build=${build}";
-#    CFLAGS="${CFLAGS} --host=${host}";
-#    CFLAGS="${CFLAGS} --target=${target}";
+    CFLAGS="-arch ${arch}";
     CFLAGS="${CFLAGS} -pipe";
     CFLAGS="${CFLAGS} -no-cpp-precomp";
-    CFLAGS="${CFLAGS} -I${SDK_DIR}/usr/include/ ";
-#    CFLAGS="${CFLAGS}-isysroot ${SDK_DIR} ";
-#    CFLAGS="${CFLAGS}\"";
+    CFLAGS="${CFLAGS} -mios-version-min=${SDKVER}";
+    CFLAGS="${CFLAGS} -I${SDK_DIR}/usr/include";
 
     LDFLAGS="-L${SDK_DIR}/usr/lib";
     LDFLAGS="${LDFLAGS} -L${SDK_DIR}/usr/lib/system";
-    DYLD_LIBRARY_PATH="${SDK_DIR}/usr/lib";
-
-    LD_LIBRARY_PATH="${SDK_DIR}/usr/lib";
+    LDFLAGS="${LDFLAGS} -L${SDK_DIR}/usr/lib/system/host";
+    LDFLAGS="${LDFLAGS} -F${SDK_DIR}/System/Library/Frameworks";
+    LDFLAGS="${LDFLAGS} -F${SDK_DIR}/System/Library/Frameworks/CoreServices";
 
     export CFLAGS="${CFLAGS}";
     export LDFLAGS="${LDFLAGS}";
-    export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}";
-    export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}";
 
     CONFIGOPTIONS="";
     CONFIGOPTIONS="${CONFIGOPTIONS} --prefix=${PREFIX}";
@@ -84,8 +76,8 @@ for arch in ${ARCHS}; do
     CONFIGOPTIONS="${CONFIGOPTIONS} --with-ar=${ar}";
     CONFIGOPTIONS="${CONFIGOPTIONS} --with-gnu-ld";
     CONFIGOPTIONS="${CONFIGOPTIONS} --with-openssl=${OPENSSLDIR}";
-#    CONFIGOPTIONS="${CONFIGOPTIONS} --with-cflags=${SDK_DIR}/usr/include";
-#    CONFIGOPTIONS="${CONFIGOPTIONS} --with-ldflags=${SDK_DIR}/usr/lib";
+#    CONFIGOPTIONS="${CONFIGOPTIONS} --with-cflags=\"${CFLAGS}\"";
+#    CONFIGOPTIONS="${CONFIGOPTIONS} --with-ldflags=${LDFLAGS}";
     CONFIGOPTIONS="${CONFIGOPTIONS} --enable-reentrant";
     CONFIGOPTIONS="${CONFIGOPTIONS} --disable-embedded-perl";
     CONFIGOPTIONS="${CONFIGOPTIONS} --disable-perl-cc-checks";
@@ -97,16 +89,16 @@ for arch in ${ARCHS}; do
     CONFIGOPTIONS="${CONFIGOPTIONS} --disable-mibs";
     CONFIGOPTIONS="${CONFIGOPTIONS} --disable-snmptrapd-subagent";
 
-    #export LIBTOOL="${CROSS_DEVELOPER}/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool";
-
-    #host="x86_64-apple-darwin12.5.0"
-    #CONFIG_OPTIONS="--prefix=${PREFIX} --host=${host} --enable-reentrant --disable-shared --with-random=/dev/urandom --disable-agent --disable-applications --disable-manuals --disable-scripts --disable-mibs"
-
     echo "./configure ${CONFIGOPTIONS}"
     ./configure ${CONFIGOPTIONS}
 
-    exit 0;
+    if [[ 0 != $? ]]; then
+        echo "failed arch:${arch}.";
+        exit 1;
+    fi
 done
+
+exit 0;
 
 mkdir -p ${MAKE_LOGS} ${NETSNMPDIR};
 
